### ISSUE TITLE
Buildpack does not work with paketo-buildpacks/nginx: 0.6.0

### ISSUE THREAD

**Issue by DmyMi** [paketo-community/staticfile#201]
When i use paketo-buildpacks/nginx version **0.5.3** and paketo-community/staticfile version **0.2.0** to build an image everything works as expected and container starts without issues. But when i build an image with newer paketo-buildpacks/nginx:0.6.0 & paketo-community/staticfile:0.2.0 the resulting container exists with the following error:
`[emerg] 1#0: open() "/workspace/logs/nginx/error.log" failed (2: No such file or directory)`

**Comment by sophiewigmore** [comment]
This looks like the same error as this issue: https://github.com/paketo-buildpacks/nginx/issues/363
@paketo-community/web-servers-maintainers

**Comment by TisVictress** [comment]
@paketo-community/web-servers-maintainers The nginx buildpack **_used to_** create the `profile.d` directory with permission bits `0755`. The staticfile buildpack creates it with `0744` if it does not already exist. Could this be the problem? Both errors seem to be related to the [logging init script](https://github.com/paketo-community/staticfile/blob/972c863b10f78adae8715f592b314aad7b2c77a5/profile_d_writer.go#L25) not being executed.
