### ISSUE TITLE
Automatic release process is broken

### ISSUE THREAD

**Issue by stephanabel** [paketo-community/staticfile#208]
Hi there,

the last automatic Release was on 25 Oct 2021.
Since then the Release Process seems to be broken, as you can see here:

"Error: PR 162 has no semver label"
(Example: https://github.com/paketo-community/staticfile/runs/6381340704?check_suite_focus=true)

Looking back at some of the PR's it seems that the bot failed to run the "auto-semver-label" actions:

"You are not logged into any GitHub hosts. Run gh auth login to authenticate. No Github credentials provided."
(Example: https://github.com/paketo-community/staticfile/runs/5724351264)

This leads to missing labels, which leads to the broken Release Tasks.

Could you take a look into this?

**Comment by ryanmoran** [comment]
cc/ @paketo-community/web-servers-maintainers @paketo-community/web-servers-contributors

**Comment by ForestEckhardt** [comment]
Alright. After a quick re-release, `v.0.3.0` should be live! I believe that both of the issues you see have been resolved. If you see any other troubles please let us know! I am going to close this issue for the time being but feel free reopen or create a new issue.
