### ISSUE TITLE
NGINX root directory should be configurable

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/staticfile#38]
The README in this repo implies that I can specify the root directory that NGINX will use to serve assets from. The following buildpack.yml structure currently errors out.
```
staticfile:
  nginx:
    root: "dist/hello-world"
```

Looks like it's just hardcoded to serve assets from ["public" directory](https://github.com/paketo-community/staticfile/blob/main/server_configs/nginx.conf#L113)

**Comment by joshzarrabi** [comment]
resolved by https://github.com/paketo-community/staticfile/pull/56
